from __future__ import annotations
import uuid
from datetime import date, datetime
from sqlalchemy import Boolean, Date, DateTime, Float, ForeignKey, Index, Integer, String, Table, Text, Column
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.core.database import Base

def uid() -> str: return str(uuid.uuid4())
def now() -> datetime: return datetime.utcnow()

episode_procedures = Table("episode_procedures", Base.metadata,
    Column("episode_id", String(36), ForeignKey("episodes.id", ondelete="CASCADE"), primary_key=True),
    Column("procedure_id", String(36), ForeignKey("procedures.id", ondelete="CASCADE"), primary_key=True))
episode_diagnoses = Table("episode_diagnoses", Base.metadata,
    Column("episode_id", String(36), ForeignKey("episodes.id", ondelete="CASCADE"), primary_key=True),
    Column("diagnosis_id", String(36), ForeignKey("diagnoses.id", ondelete="CASCADE"), primary_key=True))
visit_residents = Table("visit_residents", Base.metadata,
    Column("visit_id", String(36), ForeignKey("visits.id", ondelete="CASCADE"), primary_key=True),
    Column("clinician_id", String(36), ForeignKey("clinicians.id", ondelete="CASCADE"), primary_key=True))

class User(Base):
    __tablename__="users"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); email:Mapped[str]=mapped_column(String,unique=True,index=True); name:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=now)
class Patient(Base):
    __tablename__="patients"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); medical_record_number:Mapped[str]=mapped_column(String); medical_record_number_normalized:Mapped[str]=mapped_column(String,index=True,unique=True); title:Mapped[str|None]=mapped_column(String); full_name:Mapped[str]=mapped_column(String,index=True); sex:Mapped[str|None]=mapped_column(String); date_of_birth:Mapped[date|None]=mapped_column(Date); age_at_first_record:Mapped[int|None]=mapped_column(Integer); age_unit:Mapped[str|None]=mapped_column(String); insurance:Mapped[str|None]=mapped_column(String); primary_hospital:Mapped[str|None]=mapped_column(String); drive_folder_id:Mapped[str|None]=mapped_column(String); drive_folder_url:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now); created_by:Mapped[str|None]=mapped_column(String); is_active:Mapped[bool]=mapped_column(Boolean,default=True); episodes:Mapped[list[Episode]]=relationship(back_populates="patient")
class Clinician(Base):
    __tablename__="clinicians"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); full_name:Mapped[str]=mapped_column(String); normalized_name:Mapped[str]=mapped_column(String,index=True,unique=True); role:Mapped[str|None]=mapped_column(String)
class Procedure(Base):
    __tablename__="procedures"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String); normalized_name:Mapped[str]=mapped_column(String,index=True,unique=True); category:Mapped[str|None]=mapped_column(String)
class Diagnosis(Base):
    __tablename__="diagnoses"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String); normalized_name:Mapped[str]=mapped_column(String,index=True,unique=True)
class Episode(Base):
    __tablename__="episodes"; __table_args__=(Index("ix_episode_patient_number","patient_id","episode_number",unique=True),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); patient_id:Mapped[str]=mapped_column(ForeignKey("patients.id"),index=True); episode_number:Mapped[str]=mapped_column(String); title:Mapped[str]=mapped_column(String); primary_diagnosis:Mapped[str|None]=mapped_column(Text); start_date:Mapped[date|None]=mapped_column(Date); end_date:Mapped[date|None]=mapped_column(Date); status:Mapped[str]=mapped_column(String,default="Active"); hospital:Mapped[str|None]=mapped_column(String); primary_dpjp_id:Mapped[str|None]=mapped_column(ForeignKey("clinicians.id")); drive_folder_id:Mapped[str|None]=mapped_column(String); drive_folder_url:Mapped[str|None]=mapped_column(String); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now); created_by:Mapped[str|None]=mapped_column(String); patient:Mapped[Patient]=relationship(back_populates="episodes"); procedures:Mapped[list[Procedure]]=relationship(secondary=episode_procedures); diagnoses:Mapped[list[Diagnosis]]=relationship(secondary=episode_diagnoses); visits:Mapped[list[Visit]]=relationship(back_populates="episode")
class Visit(Base):
    __tablename__="visits"; __table_args__=(Index("ix_visit_dedupe","patient_id","episode_id","visit_date","visit_type","pod_number"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); patient_id:Mapped[str]=mapped_column(ForeignKey("patients.id"),index=True); episode_id:Mapped[str]=mapped_column(ForeignKey("episodes.id"),index=True); visit_date:Mapped[date]=mapped_column(Date,index=True); visit_type:Mapped[str]=mapped_column(String); pod_number:Mapped[int|None]=mapped_column(Integer,index=True); pod_roman:Mapped[str|None]=mapped_column(String); location:Mapped[str|None]=mapped_column(String); hospital:Mapped[str|None]=mapped_column(String); subjective:Mapped[str|None]=mapped_column(Text); objective_raw:Mapped[str|None]=mapped_column(Text); assessment:Mapped[str|None]=mapped_column(Text); plan:Mapped[str|None]=mapped_column(Text); proposal:Mapped[str|None]=mapped_column(Text); original_soap:Mapped[str]=mapped_column(Text); raw_header:Mapped[str|None]=mapped_column(Text); dpjp_id:Mapped[str|None]=mapped_column(ForeignKey("clinicians.id")); general_condition:Mapped[str|None]=mapped_column(String); consciousness:Mapped[str|None]=mapped_column(String); blood_pressure_systolic:Mapped[int|None]=mapped_column(Integer); blood_pressure_diastolic:Mapped[int|None]=mapped_column(Integer); heart_rate:Mapped[int|None]=mapped_column(Integer); respiratory_rate:Mapped[int|None]=mapped_column(Integer); temperature_celsius:Mapped[float|None]=mapped_column(Float); spo2_percent:Mapped[int|None]=mapped_column(Integer); oxygen_support:Mapped[str|None]=mapped_column(String); extraoral:Mapped[str|None]=mapped_column(Text); intraoral:Mapped[str|None]=mapped_column(Text); drive_folder_id:Mapped[str|None]=mapped_column(String); drive_folder_url:Mapped[str|None]=mapped_column(String); save_state:Mapped[str]=mapped_column(String,default="draft"); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now); created_by:Mapped[str|None]=mapped_column(String); is_deleted:Mapped[bool]=mapped_column(Boolean,default=False); deleted_at:Mapped[datetime|None]=mapped_column(DateTime); deleted_by:Mapped[str|None]=mapped_column(String); episode:Mapped[Episode]=relationship(back_populates="visits"); residents:Mapped[list[Clinician]]=relationship(secondary=visit_residents); media:Mapped[list[Media]]=relationship(back_populates="visit")
class Media(Base):
    __tablename__="media"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); visit_id:Mapped[str]=mapped_column(ForeignKey("visits.id"),index=True); drive_file_id:Mapped[str|None]=mapped_column(String,unique=True); drive_url:Mapped[str|None]=mapped_column(String); original_filename:Mapped[str]=mapped_column(String); stored_filename:Mapped[str]=mapped_column(String); mime_type:Mapped[str]=mapped_column(String); file_size:Mapped[int]=mapped_column(Integer); width:Mapped[int|None]=mapped_column(Integer); height:Mapped[int|None]=mapped_column(Integer); category:Mapped[str]=mapped_column(String,default="Uncategorized"); sequence_number:Mapped[int]=mapped_column(Integer); created_at:Mapped[datetime]=mapped_column(DateTime,default=now); uploaded_by:Mapped[str|None]=mapped_column(String); is_deleted:Mapped[bool]=mapped_column(Boolean,default=False); visit:Mapped[Visit]=relationship(back_populates="media")
class AuditLog(Base):
    __tablename__="audit_logs"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str|None]=mapped_column(String); action:Mapped[str]=mapped_column(String); entity_type:Mapped[str]=mapped_column(String); entity_id:Mapped[str]=mapped_column(String,index=True); timestamp:Mapped[datetime]=mapped_column(DateTime,default=now); before_json:Mapped[str|None]=mapped_column(Text); after_json:Mapped[str|None]=mapped_column(Text)
class AppSetting(Base):
    __tablename__="app_settings"; key:Mapped[str]=mapped_column(String,primary_key=True); value:Mapped[str]=mapped_column(Text); updated_at:Mapped[datetime]=mapped_column(DateTime,default=now,onupdate=now)
